LIB_DIR=lib
# check if exist parameter, use it
if [ -n "$1" ]; then
    # check if option is help
    if [ "$1" == "help" ]; then
        echo "Usage: ./CLEAN.sh [deep|help]"
        echo "- deep: Remove all files generated by the build and all libraries"
        echo "- help: Show this help"
        echo "- none: Remove all files generated by the build"
        echo "Example: ./CLEAN.sh deep"
        exit 0
    fi

    # check if option is deep
    if [ "$1" == "deep" ]; then
        # remove all libraries
        bash $LIB_DIR/uninstall.sh

        # Check if the uninstall was successful
        if [ $? -eq 0 ]; then
            echo "✅ Uninstall complete."
        else
            echo "❌ Uninstall failed."
            exit 1
        fi
    fi
fi

make cleanall